[2024-11-23T16:37:06.401+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T16:37:07.007+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: export_data_to_csv.export_data_to_csv scheduled__2024-11-21T06:00:00+00:00 [queued]>
[2024-11-23T16:37:07.824+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: export_data_to_csv.export_data_to_csv scheduled__2024-11-21T06:00:00+00:00 [queued]>
[2024-11-23T16:37:07.836+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-23T16:37:08.548+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): export_data_to_csv> on 2024-11-21 06:00:00+00:00
[2024-11-23T16:37:08.782+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=96) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-23T16:37:08.880+0000] {standard_task_runner.py:72} INFO - Started process 140 to run task
[2024-11-23T16:37:09.348+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'export_data_to_csv', 'export_data_to_csv', 'scheduled__2024-11-21T06:00:00+00:00', '--job-id', '792', '--raw', '--subdir', 'DAGS_FOLDER/extract_data.py', '--cfg-path', '/tmp/tmp9b57ao_c']
[2024-11-23T16:37:09.377+0000] {standard_task_runner.py:105} INFO - Job 792: Subtask export_data_to_csv
[2024-11-23T16:37:10.389+0000] {task_command.py:467} INFO - Running <TaskInstance: export_data_to_csv.export_data_to_csv scheduled__2024-11-21T06:00:00+00:00 [running]> on host e6bda0a190de
[2024-11-23T16:37:13.275+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='export_data_to_csv' AIRFLOW_CTX_TASK_ID='export_data_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-21T06:00:00+00:00'
[2024-11-23T16:37:13.293+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-23T16:37:13.295+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-23T16:37:13.309+0000] {logging_mixin.py:190} INFO - Current task name:export_data_to_csv state:running start_date:2024-11-23 16:37:07.069811+00:00
[2024-11-23T16:37:13.315+0000] {logging_mixin.py:190} INFO - Dag name:export_data_to_csv and current dag run status:running
[2024-11-23T16:37:13.324+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T16:37:15.080+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_data.py", line 39, in export_data_to_csv
    client = MongoClient(mongodb_uri)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 780, in __init__
    res = uri_parser.parse_uri(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/uri_parser.py", line 558, in parse_uri
    nodes = dns_resolver.get_hosts()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 140, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 120, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 114, in _resolve_uri
    raise ConfigurationError(str(exc)) from None
pymongo.errors.ConfigurationError: module 'httpcore' has no attribute '_backends'
[2024-11-23T16:37:15.421+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-23T16:37:15.427+0000] {logging_mixin.py:190} INFO - Task start:2024-11-23 16:37:07.069811+00:00 end:2024-11-23 16:37:15.372009+00:00 duration:8.302198
[2024-11-23T16:37:15.430+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): export_data_to_csv> dag:<DAG: export_data_to_csv> dagrun:<DagRun export_data_to_csv @ 2024-11-21 06:00:00+00:00: scheduled__2024-11-21T06:00:00+00:00, state:running, queued_at: 2024-11-23 16:33:21.207032+00:00. externally triggered: False>
[2024-11-23T16:37:15.431+0000] {logging_mixin.py:190} INFO - Failure caused by module 'httpcore' has no attribute '_backends'
[2024-11-23T16:37:15.433+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=export_data_to_csv, task_id=export_data_to_csv, run_id=scheduled__2024-11-21T06:00:00+00:00, execution_date=20241121T060000, start_date=20241123T163707, end_date=20241123T163715
[2024-11-23T16:37:15.028+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T16:37:15.042+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 792 for task export_data_to_csv (module 'httpcore' has no attribute '_backends'; 140)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_data.py", line 39, in export_data_to_csv
    client = MongoClient(mongodb_uri)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 780, in __init__
    res = uri_parser.parse_uri(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/uri_parser.py", line 558, in parse_uri
    nodes = dns_resolver.get_hosts()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 140, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 120, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 114, in _resolve_uri
    raise ConfigurationError(str(exc)) from None
pymongo.errors.ConfigurationError: module 'httpcore' has no attribute '_backends'
[2024-11-23T16:37:15.233+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-23T16:37:15.350+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T16:37:15.397+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
