[2024-11-20T08:12:04.011+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-20T08:12:04.065+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: app_data_pipeline_fin.fetch_and_store_data scheduled__2024-11-19T16:00:00+00:00 [queued]>
[2024-11-20T08:12:04.089+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: app_data_pipeline_fin.fetch_and_store_data scheduled__2024-11-19T16:00:00+00:00 [queued]>
[2024-11-20T08:12:04.091+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-20T08:12:04.123+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_store_data> on 2024-11-19 16:00:00+00:00
[2024-11-20T08:12:04.152+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=87) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-20T08:12:04.155+0000] {standard_task_runner.py:72} INFO - Started process 123 to run task
[2024-11-20T08:12:04.195+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'app_data_pipeline_fin', 'fetch_and_store_data', 'scheduled__2024-11-19T16:00:00+00:00', '--job-id', '781', '--raw', '--subdir', 'DAGS_FOLDER/insert_data_fin.py', '--cfg-path', '/tmp/tmp6kyngj8d']
[2024-11-20T08:12:04.200+0000] {standard_task_runner.py:105} INFO - Job 781: Subtask fetch_and_store_data
[2024-11-20T08:12:05.278+0000] {task_command.py:467} INFO - Running <TaskInstance: app_data_pipeline_fin.fetch_and_store_data scheduled__2024-11-19T16:00:00+00:00 [running]> on host e6bda0a190de
[2024-11-20T08:12:05.749+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='app_data_pipeline_fin' AIRFLOW_CTX_TASK_ID='fetch_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-19T16:00:00+00:00'
[2024-11-20T08:12:05.761+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-20T08:12:05.763+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-20T08:12:05.764+0000] {logging_mixin.py:190} INFO - Current task name:fetch_and_store_data state:running start_date:2024-11-20 08:12:04.066955+00:00
[2024-11-20T08:12:05.765+0000] {logging_mixin.py:190} INFO - Dag name:app_data_pipeline_fin and current dag run status:running
[2024-11-20T08:12:05.767+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-20T08:12:07.509+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/insert_data_fin.py", line 113, in fetch_and_store_data
    mongo_pipeline = MongoDBPipeline()
                     ^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/insert_data_fin.py", line 63, in __init__
    self.client = MongoClient(self.mongodb_uri)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 780, in __init__
    res = uri_parser.parse_uri(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/uri_parser.py", line 558, in parse_uri
    nodes = dns_resolver.get_hosts()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 140, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 120, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 114, in _resolve_uri
    raise ConfigurationError(str(exc)) from None
pymongo.errors.ConfigurationError: module 'httpcore' has no attribute '_backends'
[2024-11-20T08:12:07.597+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-20T08:12:07.599+0000] {logging_mixin.py:190} INFO - Task start:2024-11-20 08:12:04.066955+00:00 end:2024-11-20 08:12:07.596652+00:00 duration:3.529697
[2024-11-20T08:12:07.600+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_and_store_data> dag:<DAG: app_data_pipeline_fin> dagrun:<DagRun app_data_pipeline_fin @ 2024-11-19 16:00:00+00:00: scheduled__2024-11-19T16:00:00+00:00, state:running, queued_at: 2024-11-20 08:09:50.078441+00:00. externally triggered: False>
[2024-11-20T08:12:07.601+0000] {logging_mixin.py:190} INFO - Failure caused by module 'httpcore' has no attribute '_backends'
[2024-11-20T08:12:07.602+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=app_data_pipeline_fin, task_id=fetch_and_store_data, run_id=scheduled__2024-11-19T16:00:00+00:00, execution_date=20241119T160000, start_date=20241120T081204, end_date=20241120T081207
[2024-11-20T08:12:07.681+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-20T08:12:07.683+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 781 for task fetch_and_store_data (module 'httpcore' has no attribute '_backends'; 123)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/insert_data_fin.py", line 113, in fetch_and_store_data
    mongo_pipeline = MongoDBPipeline()
                     ^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/insert_data_fin.py", line 63, in __init__
    self.client = MongoClient(self.mongodb_uri)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 780, in __init__
    res = uri_parser.parse_uri(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/uri_parser.py", line 558, in parse_uri
    nodes = dns_resolver.get_hosts()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 140, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 120, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 114, in _resolve_uri
    raise ConfigurationError(str(exc)) from None
pymongo.errors.ConfigurationError: module 'httpcore' has no attribute '_backends'
[2024-11-20T08:12:07.736+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-20T08:12:07.801+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-20T08:12:07.805+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
