[2024-11-19T08:22:27.687+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-19T08:22:27.751+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: app_data_pipeline_8h.run_script_data_news scheduled__2024-11-17T16:00:00+00:00 [queued]>
[2024-11-19T08:22:27.789+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: app_data_pipeline_8h.run_script_data_news scheduled__2024-11-17T16:00:00+00:00 [queued]>
[2024-11-19T08:22:27.791+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-19T08:22:27.835+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_script_data_news> on 2024-11-17 16:00:00+00:00
[2024-11-19T08:22:27.866+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=236) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-19T08:22:27.874+0000] {standard_task_runner.py:72} INFO - Started process 266 to run task
[2024-11-19T08:22:27.871+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'app_data_pipeline_8h', 'run_script_data_news', 'scheduled__2024-11-17T16:00:00+00:00', '--job-id', '739', '--raw', '--subdir', 'DAGS_FOLDER/insert_data_news.py', '--cfg-path', '/tmp/tmpvfq71le3']
[2024-11-19T08:22:27.878+0000] {standard_task_runner.py:105} INFO - Job 739: Subtask run_script_data_news
[2024-11-19T08:22:28.230+0000] {task_command.py:467} INFO - Running <TaskInstance: app_data_pipeline_8h.run_script_data_news scheduled__2024-11-17T16:00:00+00:00 [running]> on host 6f0acbd85128
[2024-11-19T08:22:28.526+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='app_data_pipeline_8h' AIRFLOW_CTX_TASK_ID='run_script_data_news' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-17T16:00:00+00:00'
[2024-11-19T08:22:28.532+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-19T08:22:28.534+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-19T08:22:28.535+0000] {logging_mixin.py:190} INFO - Current task name:run_script_data_news state:running start_date:2024-11-19 08:22:27.752255+00:00
[2024-11-19T08:22:28.536+0000] {logging_mixin.py:190} INFO - Dag name:app_data_pipeline_8h and current dag run status:running
[2024-11-19T08:22:28.537+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-19T08:22:29.462+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/insert_data_news.py", line 116, in run_script
    main()
  File "/opt/airflow/dags/insert_data_news.py", line 102, in main
    mongo_pipeline = MongoDBPipeline()
                     ^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/insert_data_news.py", line 52, in __init__
    self.client = MongoClient(self.mongodb_uri)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 780, in __init__
    res = uri_parser.parse_uri(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/uri_parser.py", line 558, in parse_uri
    nodes = dns_resolver.get_hosts()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 140, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 120, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 114, in _resolve_uri
    raise ConfigurationError(str(exc)) from None
pymongo.errors.ConfigurationError: module 'httpcore' has no attribute '_backends'
[2024-11-19T08:22:29.576+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-19T08:22:29.579+0000] {logging_mixin.py:190} INFO - Task start:2024-11-19 08:22:27.752255+00:00 end:2024-11-19 08:22:29.574462+00:00 duration:1.822207
[2024-11-19T08:22:29.581+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): run_script_data_news> dag:<DAG: app_data_pipeline_8h> dagrun:<DagRun app_data_pipeline_8h @ 2024-11-17 16:00:00+00:00: scheduled__2024-11-17T16:00:00+00:00, state:running, queued_at: 2024-11-19 08:20:53.373748+00:00. externally triggered: False>
[2024-11-19T08:22:29.582+0000] {logging_mixin.py:190} INFO - Failure caused by module 'httpcore' has no attribute '_backends'
[2024-11-19T08:22:29.593+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=app_data_pipeline_8h, task_id=run_script_data_news, run_id=scheduled__2024-11-17T16:00:00+00:00, execution_date=20241117T160000, start_date=20241119T082227, end_date=20241119T082229
[2024-11-19T08:22:29.678+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-19T08:22:29.685+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 739 for task run_script_data_news (module 'httpcore' has no attribute '_backends'; 266)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/insert_data_news.py", line 116, in run_script
    main()
  File "/opt/airflow/dags/insert_data_news.py", line 102, in main
    mongo_pipeline = MongoDBPipeline()
                     ^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/insert_data_news.py", line 52, in __init__
    self.client = MongoClient(self.mongodb_uri)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 780, in __init__
    res = uri_parser.parse_uri(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/uri_parser.py", line 558, in parse_uri
    nodes = dns_resolver.get_hosts()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 140, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 120, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/srv_resolver.py", line 114, in _resolve_uri
    raise ConfigurationError(str(exc)) from None
pymongo.errors.ConfigurationError: module 'httpcore' has no attribute '_backends'
[2024-11-19T08:22:29.764+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-19T08:22:29.820+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-19T08:22:29.828+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
