[2024-11-20T08:15:19.579+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-20T08:15:19.613+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: export_data_to_csv.export_data_to_csv scheduled__2024-11-19T06:00:00+00:00 [queued]>
[2024-11-20T08:15:19.626+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: export_data_to_csv.export_data_to_csv scheduled__2024-11-19T06:00:00+00:00 [queued]>
[2024-11-20T08:15:19.627+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-20T08:15:19.643+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): export_data_to_csv> on 2024-11-19 06:00:00+00:00
[2024-11-20T08:15:19.655+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=169) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-20T08:15:19.657+0000] {standard_task_runner.py:72} INFO - Started process 174 to run task
[2024-11-20T08:15:19.664+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'export_data_to_csv', 'export_data_to_csv', 'scheduled__2024-11-19T06:00:00+00:00', '--job-id', '783', '--raw', '--subdir', 'DAGS_FOLDER/extract_data.py', '--cfg-path', '/tmp/tmp79ybygrx']
[2024-11-20T08:15:19.666+0000] {standard_task_runner.py:105} INFO - Job 783: Subtask export_data_to_csv
[2024-11-20T08:15:19.859+0000] {task_command.py:467} INFO - Running <TaskInstance: export_data_to_csv.export_data_to_csv scheduled__2024-11-19T06:00:00+00:00 [running]> on host e6bda0a190de
[2024-11-20T08:15:20.048+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='export_data_to_csv' AIRFLOW_CTX_TASK_ID='export_data_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-19T06:00:00+00:00'
[2024-11-20T08:15:20.052+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-20T08:15:20.053+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-20T08:15:20.053+0000] {logging_mixin.py:190} INFO - Current task name:export_data_to_csv state:running start_date:2024-11-20 08:15:19.613803+00:00
[2024-11-20T08:15:20.054+0000] {logging_mixin.py:190} INFO - Dag name:export_data_to_csv and current dag run status:running
[2024-11-20T08:15:20.056+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-20T08:15:21.352+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_data.py", line 71, in export_data_to_csv
    df_fin.to_csv(os.path.join(output_dir, 'data_finance.csv'), index=False, encoding='utf-8')
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/opt/***/dags/../data'
[2024-11-20T08:15:21.396+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-20T08:15:21.397+0000] {logging_mixin.py:190} INFO - Task start:2024-11-20 08:15:19.613803+00:00 end:2024-11-20 08:15:21.394646+00:00 duration:1.780843
[2024-11-20T08:15:21.397+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): export_data_to_csv> dag:<DAG: export_data_to_csv> dagrun:<DagRun export_data_to_csv @ 2024-11-19 06:00:00+00:00: scheduled__2024-11-19T06:00:00+00:00, state:running, queued_at: 2024-11-20 08:09:47.477330+00:00. externally triggered: False>
[2024-11-20T08:15:21.398+0000] {logging_mixin.py:190} INFO - Failure caused by Cannot save file into a non-existent directory: '/opt/***/dags/../data'
[2024-11-20T08:15:21.399+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=export_data_to_csv, task_id=export_data_to_csv, run_id=scheduled__2024-11-19T06:00:00+00:00, execution_date=20241119T060000, start_date=20241120T081519, end_date=20241120T081521
[2024-11-20T08:15:21.422+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-20T08:15:21.423+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 783 for task export_data_to_csv (Cannot save file into a non-existent directory: '/opt/***/dags/../data'; 174)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_data.py", line 71, in export_data_to_csv
    df_fin.to_csv(os.path.join(output_dir, 'data_finance.csv'), index=False, encoding='utf-8')
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/opt/***/dags/../data'
[2024-11-20T08:15:21.483+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-20T08:15:21.521+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-20T08:15:21.526+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
